Add send/get message to nodejs agent, fix logging
AbsaOSS/libvcx pull request #95
Opened 2020-09-20 10:18 UTC by Patrik-Stas

Signed-off-by: Patrik Stas <patrik.stas@absa.africa>

2020-09-20 11:01 UTC, mirgee requested changes

2020-09-20 15:05 UTC, Patrik-Stas commented on agents/node/vcxagent-core/messages.js
> +  const donwloadInstructions = {
This is JS ;-)

2020-09-20 15:19 UTC, Patrik-Stas commented on agents/node/vcxagent-core/messages.js
> +    throw Error('Unexpected to get more than 1 items from download messages for single pairwise did')
What you've suggested is not what the error is supposed to express, however I tweaked the messages a bit.

2020-09-20 15:21 UTC, Patrik-Stas commented on agents/node/vcxagent-core/messages.js
> +module.exports.messagesGetForPwDid = async function messagesGetForPwDid (
renamed

2020-09-20 16:29 UTC, mirgee commented on agents/node/vcxagent-core/messages.js
> +  const donwloadInstructions = {
Sorry, the point was supposed to be that there is a typo :)

2020-09-20 19:15 UTC, Patrik-Stas commented on agents/node/vcxagent-core/messages.js
> +  const donwloadInstructions = {
Ahha thanks, I missed that. Fixed now.

2020-09-22 10:19 UTC, mirgee approved these changes

2020-09-22 10:21 UTC, merged